import { StyleSheet } from 'react-native';

// KitchenScreen.js 에서 분리된 스타일 시트.
// scale: useResponsive() 의 폰트 배율(lg=1.3, 그 외 1.0). PC/대형 태블릿 가독성 향상용.
//        주방 디스플레이는 멀리서 보는 용도라 가독성 효과가 가장 큰 화면.
export default function makeStyles(scale = 1) {
  const fp = (n) => Math.round(n * scale);
  return StyleSheet.create({
  // 카드 영역(좌) + 조리 대기 사이드바(우) 가로 분할
  bodyRow: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#f5f6f8',
  },
  // 웹: 마우스 드래그 가능 영역 표시 + 드래그 시 텍스트 선택 방지 + 스크롤바 항상 표시
  scrollWeb: {
    cursor: 'grab',
    userSelect: 'none',
    overflowY: 'scroll',
  },
  sidebar: {
    backgroundColor: '#fef9f0',
    borderWidth: 2,
    borderColor: '#f59e0b',
    borderRadius: 12,
    margin: 6,
    flexShrink: 0,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  // 헤더: 주황 → 빨강 그라디언트 톤 + 아이콘
  sidebarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: '#ea580c',
    gap: 6,
    borderBottomWidth: 2,
    borderBottomColor: '#c2410c',
  },
  sidebarHeaderIcon: {
    fontSize: fp(14),
  },
  sidebarTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: fp(13),
    fontWeight: '900',
    color: '#fff',
    letterSpacing: 0,
    textShadowColor: 'rgba(0,0,0,0.25)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  sidebarTotalQty: {
    fontSize: fp(12),
    fontWeight: '900',
    color: '#7c2d12',
    backgroundColor: '#fde68a',
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: 12,
    overflow: 'hidden',
  },
  sidebarList: {
    flex: 1,
  },
  sidebarEmpty: {
    fontSize: fp(12),
    color: '#9ca3af',
    textAlign: 'center',
    paddingVertical: 24,
  },
  sidebarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
    borderLeftWidth: 5,
    gap: 5,
  },
  sidebarRowActive: {
    borderLeftWidth: 7,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
  },
  sidebarColorDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    flexShrink: 0,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.18)',
  },
  sidebarRowTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  sidebarRowName: {
    fontSize: fp(12),
    color: '#111827',
    fontWeight: '800',
  },
  sidebarRowOpts: {
    fontSize: fp(10),
    color: '#1d4ed8',
    fontWeight: '700',
    marginTop: 1,
  },
  sidebarRowQtyWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    flexShrink: 0,
  },
  sidebarRowLargeBadge: {
    fontSize: fp(9),
    color: '#fff',
    fontWeight: '900',
    backgroundColor: '#dc2626',
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
    overflow: 'hidden',
  },
  sidebarRowNormalBadge: {
    fontSize: fp(9),
    color: '#1e3a8a',
    fontWeight: '900',
    backgroundColor: '#dbeafe',
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
    overflow: 'hidden',
  },
  sidebarRowQty: {
    fontSize: fp(14),
    fontWeight: '900',
    color: '#b91c1c',
    fontVariant: ['tabular-nums'],
    minWidth: 28,
    textAlign: 'right',
  },
  empty: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    padding: 24,
  },
  emptyTitle: { fontSize: fp(22), fontWeight: '700', color: '#111827', marginBottom: 8 },
  emptyText: { fontSize: fp(14), color: '#6b7280' },
  versionMark: { fontSize: fp(10), color: '#9ca3af', marginTop: 12 },
  versionBar: {
    width: '100%',
    paddingVertical: 4,
    alignItems: 'center',
    marginBottom: -8,
  },
  versionText: {
    fontSize: fp(10),
    color: '#9ca3af',
    fontWeight: '600',
  },

  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    padding: 16,
  },
  gridPhone: { gap: 6, padding: 6 },
  card: {
    borderWidth: 2,
    borderRadius: 10,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  cardReady: { opacity: 0.6 },
  cardChanged: {
    borderWidth: 3,
    shadowColor: '#f59e0b',
    shadowOpacity: 0.35,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 0 },
  },
  cardHighlighted: {
    borderColor: '#facc15',
    borderWidth: 4,
    shadowColor: '#facc15',
    shadowOpacity: 0.6,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
    elevation: 6,
  },
  cardDimmed: { opacity: 0.35 },
  highlightBadge: {
    fontSize: fp(10),
    color: '#7c2d12',
    fontWeight: '900',
    backgroundColor: '#facc15',
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
    flexShrink: 0,
  },
  changedBadge: {
    fontSize: fp(10),
    color: '#111827',
    fontWeight: '800',
    backgroundColor: '#fde68a',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
  },
  freshBadge: {
    fontSize: fp(10),
    color: '#fff',
    fontWeight: '800',
    backgroundColor: 'rgba(0,0,0,0.35)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
  },
  deliveryBar: {
    backgroundColor: '#fef2f2',
    borderBottomWidth: 1,
    borderBottomColor: '#fecaca',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  deliveryBarLabel: {
    fontSize: fp(11),
    color: '#991b1b',
    fontWeight: '800',
    marginBottom: 2,
  },
  deliveryBarText: {
    fontSize: fp(13),
    color: '#7f1d1d',
    fontWeight: '600',
  },
  requestBar: {
    backgroundColor: '#fff7ed',
    borderBottomWidth: 1,
    borderBottomColor: '#fed7aa',
    borderLeftWidth: 4,
    borderLeftColor: '#ea580c',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  requestBarLabel: {
    fontSize: fp(11),
    color: '#9a3412',
    fontWeight: '800',
    marginBottom: 2,
  },
  requestBarText: {
    fontSize: fp(14),
    color: '#7c2d12',
    fontWeight: '800',
  },
  changeBox: {
    backgroundColor: '#fff7ed',
    borderBottomWidth: 2,
    borderBottomColor: '#f59e0b',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  changeBoxTitle: {
    fontSize: fp(13),
    color: '#b45309',
    fontWeight: '800',
    marginBottom: 4,
  },
  freshBox: {
    backgroundColor: '#ecfdf5',
    borderBottomColor: '#10b981',
  },
  freshBoxTitle: { color: '#065f46' },
  changeLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  changeTag: {
    fontSize: fp(10),
    fontWeight: '800',
    color: '#fff',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 3,
    overflow: 'hidden',
    minWidth: 32,
    textAlign: 'center',
  },
  tagAdded: { backgroundColor: '#10b981' },
  tagChanged: { backgroundColor: '#d97706' },
  tagRemoved: { backgroundColor: '#dc2626' },
  changeName: { flex: 1, fontSize: fp(13), color: '#111827', fontWeight: '600' },
  changeNameInline: { minWidth: 0 },
  changeDetailInline: {
    fontSize: fp(11),
    color: '#92400e',
    fontWeight: '700',
  },
  changeValue: { fontSize: fp(13), color: '#374151', fontWeight: '700' },
  changeDetail: {
    fontSize: fp(11),
    color: '#92400e',
    fontWeight: '700',
    marginTop: 1,
  },
  largeTag: { color: '#dc2626', fontWeight: '800' },
  normalTag: { color: '#6b7280', fontWeight: '700' },
  optTag: { color: '#2563eb', fontWeight: '700', fontSize: fp(10) },
  // 메모 — 항목 위 최상단에 노란 강조 박스
  itemMemoLine: {
    backgroundColor: '#fffbeb',
    borderLeftWidth: 3,
    borderLeftColor: '#f59e0b',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginBottom: 2,
  },
  itemMemoText: {
    fontSize: fp(12),
    color: '#92400e',
    fontWeight: '700',
  },
  itemMemoTextPhone: { fontSize: fp(10) },
  sectionLabel: {
    fontSize: fp(10),
    color: '#9ca3af',
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  row_unchanged: {},
  row_added: { backgroundColor: '#dcfce7', borderRadius: 4, paddingHorizontal: 4 },
  row_removed: { backgroundColor: '#fee2e2', borderRadius: 4, paddingHorizontal: 4 },
  row_changed: { backgroundColor: '#fef3c7', borderRadius: 4, paddingHorizontal: 4 },
  inlineTag: {
    fontSize: fp(10),
    fontWeight: '800',
    color: '#fff',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 3,
    overflow: 'hidden',
    marginRight: 6,
  },
  text_unchanged: {},
  text_added: { color: '#065f46', fontWeight: '800' },
  text_removed: { color: '#991b1b', textDecorationLine: 'line-through' },
  text_changed: { color: '#92400e', fontWeight: '800' },
  row_cooking: { backgroundColor: '#fff7ed' },
  row_cooked: { backgroundColor: '#f3f4f6', opacity: 0.8 },
  row_highlight: {
    backgroundColor: '#fef08a',
    borderRadius: 4,
    paddingHorizontal: 4,
    borderLeftWidth: 4,
    borderLeftColor: '#eab308',
  },
  text_cooking: { color: '#c2410c', fontWeight: '800' },
  text_cooked: {
    color: '#9ca3af',
    textDecorationLine: 'line-through',
    fontWeight: '500',
  },
  tagCooked: { backgroundColor: '#10b981' },
  tagCooking: { backgroundColor: '#f97316' },

  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  cardHeaderPhone: { paddingHorizontal: 6, paddingVertical: 4 },
  cardLabelPhone: { fontSize: fp(13) },
  // flex: 1 + minWidth: 0 + overflow: hidden 으로 자식들이 cardTime 영역 침범 못 함.
  // 뱃지들이 너무 많으면 우측이 잘리고, cardTime 은 항상 우측에 보임.
  headerLeft: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    overflow: 'hidden',
  },
  seqBadge: {
    fontSize: fp(11),
    color: '#fff',
    fontWeight: '700',
    backgroundColor: 'rgba(0,0,0,0.25)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
  },
  cardLabel: { fontSize: fp(16), color: '#fff', fontWeight: '800' },
  cardType: {
    fontSize: fp(11),
    color: '#fff',
    fontWeight: '700',
    backgroundColor: 'rgba(255,255,255,0.25)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
  },
  // flexShrink: 0 으로 시간이 항상 한 줄로 보이게 (두 자리 분도 안 잘림)
  cardTime: {
    flexShrink: 0,
    fontSize: fp(12),
    color: '#fff',
    fontWeight: '600',
  },

  cardBody: { paddingHorizontal: 12, paddingVertical: 10, gap: 6 },
  cardBodyPhone: { paddingHorizontal: 6, paddingVertical: 4, gap: 3 },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  itemNameWrap: { flex: 1, minWidth: 0 },
  itemName: { fontSize: fp(14), color: '#111827', fontWeight: '600' },
  // 폰 화면에서도 변경사항 영역(changeName: 13px)과 동일한 크기로 통일
  itemNamePhone: { fontSize: fp(13) },
  itemOptLine: {
    fontSize: fp(11),
    color: '#1d4ed8',
    fontWeight: '700',
    marginTop: 1,
  },
  itemOptLinePhone: { fontSize: fp(11) },
  itemQty: {
    fontSize: fp(13),
    color: '#374151',
    fontWeight: '700',
    minWidth: 32,
    textAlign: 'right',
  },
  itemQtyPhone: { fontSize: fp(13), minWidth: 28 },
  itemSubtotal: {
    fontSize: fp(12),
    color: '#6b7280',
    minWidth: 60,
    textAlign: 'right',
  },
  itemSubtotalPhone: { fontSize: fp(12), minWidth: 50 },

  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: '#eef0f3',
    gap: 8,
  },
  cardFooterPhone: { padding: 6, gap: 4 },
  totalWrap: { flex: 1 },
  totalLabel: { fontSize: fp(11), color: '#6b7280' },
  totalValue: { fontSize: fp(15), color: '#111827', fontWeight: '800' },
  totalValuePhone: { fontSize: fp(12) },
  printSlipBtn: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 6,
    backgroundColor: '#374151',
  },
  printSlipBtnText: { fontSize: fp(14) },
  doneBtn: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 6,
    backgroundColor: '#2563eb',
  },
  doneBtnPhone: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 4 },
  doneBtnReady: { backgroundColor: '#10b981' },
  doneBtnText: { color: '#fff', fontSize: fp(13), fontWeight: '700' },
  doneBtnTextPhone: { fontSize: fp(11) },
  doneBtnTextReady: { color: '#fff' },
  });
}
