import { StyleSheet } from 'react-native';

// OrderScreen.js 에서 분리된 스타일 시트.
// scale: useResponsive() 의 폰트 배율(lg=1.3, 그 외 1.0). PC/대형 태블릿 가독성 향상용.
export default function makeStyles(scale = 1) {
  const fp = (n) => Math.round(n * scale);
  return StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },

  tableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
    gap: 6,
  },
  backBtn: { paddingVertical: 4, paddingHorizontal: 8, width: 72 },
  backText: { fontSize: fp(14), color: '#374151', fontWeight: '600' },
  tableHeaderHint: { fontSize: fp(11), color: '#6b7280' },
  tableLabel: { fontSize: fp(16), color: '#111827', fontWeight: '700', flexShrink: 0 },
  headerAddressWrap: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 12,
    gap: 6,
  },

  deliveryBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#fecaca',
    backgroundColor: '#fef2f2',
    gap: 6,
  },
  deliveryLabel: {
    fontSize: fp(14),
    color: '#991b1b',
    fontWeight: '800',
  },
  deliveryInput: {
    borderWidth: 1,
    borderColor: '#fecaca',
    borderRadius: 6,
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: fp(13),
    color: '#111827',
  },
  deliveryInputFlex: { flex: 1, minWidth: 120 },
  // 헤더 인라인용 — 5~7글자 + 여유. 자주 칩이 옆에 들어갈 공간 확보.
  deliveryInputCompact: {
    width: 130,
    flexShrink: 0,
    paddingVertical: 4,
    paddingHorizontal: 8,
    fontSize: fp(12),
  },
  deliveryTimeInputCompact: {
    width: 60,
    paddingVertical: 4,
    paddingHorizontal: 6,
    fontSize: fp(12),
  },
  kbDoneBtn: {
    backgroundColor: '#10b981',
    borderRadius: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    flexShrink: 0,
    marginLeft: 4,
  },
  kbDoneBtnText: {
    color: '#fff',
    fontSize: fp(13),
    fontWeight: '700',
  },
  deliveryLabelTight: {
    fontSize: fp(13),
    color: '#991b1b',
    fontWeight: '800',
    marginLeft: 4,
  },
  addressBookBtn: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#fecaca',
    borderRadius: 6,
    backgroundColor: '#fff',
  },
  addressBookBtnText: {
    fontSize: fp(12),
    fontWeight: '900',
    color: '#991b1b',
  },
  deliveryTimeInput: {
    borderWidth: 1,
    borderColor: '#fecaca',
    borderRadius: 6,
    backgroundColor: '#fff',
    paddingHorizontal: 8,
    paddingVertical: 6,
    fontSize: fp(13),
    color: '#111827',
    width: 72,
    textAlign: 'center',
    fontWeight: '700',
  },
  deliveryHint: {
    fontSize: fp(11),
    color: '#991b1b',
    fontStyle: 'italic',
  },
  deliveryOk: {
    color: '#065f46',
    fontWeight: '700',
    fontStyle: 'normal',
  },
  deliveryErr: {
    color: '#b91c1c',
    fontWeight: '700',
    fontStyle: 'normal',
  },
  ampmGroup: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#fecaca',
    borderRadius: 6,
    overflow: 'hidden',
  },
  ampmBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#fff',
  },
  ampmBtnActive: { backgroundColor: '#dc2626' },
  ampmText: { fontSize: fp(12), fontWeight: '700', color: '#991b1b' },
  ampmTextActive: { color: '#fff' },

  body: { flex: 1, flexDirection: 'row', minHeight: 0 },
  bodyStacked: { flexDirection: 'column' },
  menuSide: { flex: 1, minHeight: 0, minWidth: 0 },
  cartSide: {
    borderLeftWidth: 1,
    borderLeftColor: '#e5e7eb',
    backgroundColor: '#fff',
  },
  cartSideStacked: {
    width: '100%',
    maxHeight: 300,
    borderLeftWidth: 0,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },

  categoryBar: {
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#fff',
  },
  categoryTab: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  categoryTabPhone: { paddingHorizontal: 8, paddingVertical: 4, borderBottomWidth: 2 },
  categoryTabActive: { borderBottomColor: '#dc2626' },
  categoryText: { fontSize: fp(15), color: '#6b7280', fontWeight: '500' },
  categoryTextPhone: { fontSize: fp(11) },
  categoryTextActive: { color: '#111827', fontWeight: '700' },

  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    padding: 10,
  },
  favGrid: {
    flex: 1,
    flexDirection: 'column',
    paddingVertical: 4,
  },
  favRow: {
    flex: 1,
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 4,
    paddingBottom: 3,
    alignItems: 'stretch',
    justifyContent: 'center',
    minHeight: 0,
  },
  tile: {
    // 타일을 바둑판처럼 정사각형 비율로 — 사진이 가로로 늘어나는 현상 방지
    aspectRatio: 1,
    borderRadius: 4,
    overflow: 'hidden',
  },
  tilePhone: { aspectRatio: 1, borderRadius: 3 },
  tileDragging: { opacity: 0.35 },
  tileDragTarget: {
    borderWidth: 3,
    borderColor: '#2563eb',
  },
  tileNativeMoving: { opacity: 0.5, borderWidth: 3, borderColor: '#f59e0b' },
  tileNativeMoveTarget: { borderWidth: 2, borderColor: '#10b981' },
  nativeMoveBanner: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#1F2937', paddingHorizontal: 12, paddingVertical: 6, gap: 8,
  },
  nativeMoveBannerText: { flex: 1, fontSize: fp(11), color: '#d1d5db', fontWeight: '600' },
  nativeMoveCancelBtn: {
    paddingHorizontal: 10, paddingVertical: 4, backgroundColor: '#374151', borderRadius: 6,
  },
  nativeMoveCancelText: { fontSize: fp(11), color: '#fff', fontWeight: '700' },
  tileEmptySlot: {
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#e5e7eb',
    borderRadius: 4,
    backgroundColor: 'rgba(0,0,0,0.02)',
  },
  favDragHint: {
    fontSize: fp(11),
    color: '#6b7280',
    fontWeight: '600',
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 8,
    fontStyle: 'italic',
  },
  tileImage: { flex: 1 },
  tileImageRadius: { borderRadius: 4 },
  tileScrimTop: {
    backgroundColor: 'rgba(0,0,0,0.55)',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  tileScrimTopPhone: { paddingHorizontal: 4, paddingVertical: 2 },
  tileScrimBottom: {
    backgroundColor: 'rgba(0,0,0,0.55)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    alignItems: 'flex-end',
  },
  tileScrimBottomPhone: { paddingHorizontal: 4, paddingVertical: 2 },
  tileName: {
    color: '#fff',
    fontSize: fp(14),
    fontWeight: '700',
    textShadowColor: 'rgba(0,0,0,0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  tileNamePhone: { fontSize: fp(10) },
  tilePrice: {
    color: '#fff',
    fontSize: fp(13),
    fontWeight: '700',
    textShadowColor: 'rgba(0,0,0,0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  tilePricePhone: { fontSize: fp(10) },

  optionsSection: {
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    backgroundColor: '#fafafa',
  },
  optionsSectionPhone: { padding: 4 },
  optionsTitle: { fontSize: fp(13), color: '#374151', marginBottom: 8, fontWeight: '600' },
  optionsTitlePhone: { fontSize: fp(10), marginBottom: 2 },
  optionsTitleFlex: { flex: 1, marginBottom: 0 },
  optionsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 6,
  },
  memoBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 5,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d1d5db',
  },
  memoBtnPhone: {
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 4,
  },
  memoBtnDisabled: { opacity: 0.4 },
  memoBtnText: {
    fontSize: fp(11),
    color: '#374151',
    fontWeight: '700',
  },
  memoBtnTextPhone: { fontSize: fp(9) },
  memoBtnTextDisabled: { color: '#9ca3af' },
  optionsEditBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 5,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d1d5db',
  },
  optionsEditBtnPhone: {
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 4,
  },
  optionsEditBtnText: { fontSize: fp(12) },
  optionsEditBtnTextPhone: { fontSize: fp(10) },
  // 메모 입력 영역
  memoInput: {
    width: '100%',
    minHeight: 64,
    maxHeight: 120,
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: fp(14),
    color: '#111827',
    textAlignVertical: 'top',
  },
  memoModalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  memoClearBtn: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d1d5db',
  },
  memoClearBtnText: { color: '#374151', fontSize: fp(13), fontWeight: '700' },
  // 옵션 편집 모달
  optionsEditCard: {
    width: '100%',
    maxWidth: 460,
    padding: 14,
    gap: 8,
    alignItems: 'stretch',
  },
  optionsEditHint: {
    fontSize: fp(11),
    color: '#6b7280',
    textAlign: 'center',
    marginBottom: 2,
  },
  optionsEditList: {
    width: '100%',
  },
  optionsEditRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 2,
  },
  optionsEditInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 6,
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: fp(13),
    color: '#111827',
  },
  optionsEditMoveBtn: {
    width: 32,
    height: 32,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionsEditMoveBtnDisabled: { opacity: 0.35 },
  optionsEditMoveBtnText: {
    fontSize: fp(14),
    color: '#374151',
    fontWeight: '700',
    lineHeight: fp(16),
  },
  cartItemMemo: {
    fontSize: fp(10),
    color: '#92400e',
    fontWeight: '600',
    backgroundColor: '#fffbeb',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
    marginTop: 1,
  },
  optionsGrid: { flexDirection: 'row', gap: 4 },
  optionBtn: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 8,
    paddingHorizontal: 4,
    borderRadius: 5,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d1d5db',
    alignItems: 'center',
  },
  optionBtnPhone: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 3,
    paddingHorizontal: 2,
    borderRadius: 4,
  },
  optionBtnActive: { backgroundColor: '#1f2937', borderColor: '#1f2937' },
  optionBtnDisabled: { opacity: 0.35 },

  // <Modal> 대체 풀스크린 오버레이
  sizeModalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 9999,
    elevation: 9999,
  },
  sizeModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(17,24,39,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  sizeModalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 24,
    gap: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 14,
    elevation: 8,
  },
  sizeModalClose: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sizeModalCloseText: { fontSize: fp(20), color: '#6b7280' },
  sizeModalLine1: {
    fontSize: fp(15),
    color: '#374151',
    fontWeight: '600',
    marginTop: 8,
  },
  sizeModalLine2: {
    fontSize: fp(17),
    color: '#111827',
    fontWeight: '800',
    textAlign: 'center',
  },
  sizeModalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
  },
  // 주문내역과 동일한 [− N +] 박스 — 모달용은 폰트만 약간 큼
  sizeStepBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  sizeStepBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sizeStepBtnText: {
    fontSize: fp(18),
    color: '#374151',
    fontWeight: '700',
    lineHeight: fp(20),
  },
  sizeStepValue: {
    fontSize: fp(16),
    color: '#111827',
    fontWeight: '800',
    minWidth: 40,
    paddingHorizontal: 6,
    textAlign: 'center',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: '#e5e7eb',
    lineHeight: 36,
  },
  sizeConfirmBtn: {
    marginLeft: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#2563eb',
  },
  sizeConfirmText: { color: '#fff', fontSize: fp(13), fontWeight: '800' },
  sizeProgress: { fontSize: fp(11), color: '#9ca3af', marginTop: 6 },
  optionLabel: { fontSize: fp(11), color: '#374151', fontWeight: '600', textAlign: 'center' },
  optionLabelPhone: { fontSize: fp(9) },
  optionLabelActive: { color: '#fff' },
  optionPrice: { fontSize: fp(10), color: '#6b7280', marginTop: 1 },
  optionPricePhone: { fontSize: fp(8), marginTop: 0 },

  cartHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    paddingVertical: 3,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#fff',
  },
  cartTitle: { fontSize: fp(10), color: '#111827', fontWeight: '700' },
  cartSubtitle: { fontSize: fp(9), color: '#6b7280', fontWeight: '600' },
  cartHeaderRight: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  micBtn: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#f3f4f6',
    borderWidth: 1,
    borderColor: '#d1d5db',
    alignItems: 'center',
    justifyContent: 'center',
  },
  micBtnActive: { backgroundColor: '#fee2e2', borderColor: '#dc2626' },
  micBtnDisabled: { opacity: 0.4 },
  micIcon: { fontSize: fp(11) },

  listeningBar: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: '#fef2f2',
    borderBottomWidth: 1,
    borderBottomColor: '#fecaca',
  },
  listeningTitle: {
    fontSize: fp(11),
    color: '#991b1b',
    fontWeight: '700',
    marginBottom: 2,
  },
  listeningText: { fontSize: fp(12), color: '#7f1d1d' },

  cartList: { flex: 1 },
  cartEmpty: {
    fontSize: fp(13),
    color: '#9ca3af',
    textAlign: 'center',
    marginTop: 40,
  },
  cartItem: {
    flexDirection: 'column',
    paddingVertical: 3,
    paddingHorizontal: 2,
    borderBottomWidth: 1,
    borderBottomColor: '#eef0f3',
    gap: 1,
  },
  cartItemTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  cartItemBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 4,
  },
  cartItemName: {
    flex: 1,
    minWidth: 0,
    fontSize: fp(12),
    lineHeight: fp(16),
    color: '#111827',
    fontWeight: '700',
  },
  largeBadge: { color: '#dc2626', fontSize: fp(10), fontWeight: '800' },
  normalInlineTag: { color: '#6b7280', fontSize: fp(10), fontWeight: '700' },
  cartItemSelected: {
    backgroundColor: '#eff6ff',
    borderLeftWidth: 3,
    borderLeftColor: '#2563eb',
    paddingLeft: 5,
  },
  cartItemOptions: {
    fontSize: fp(10),
    color: '#2563eb',
    fontWeight: '600',
  },
  cartItemPrice: {
    fontSize: fp(11),
    color: '#6b7280',
    fontVariant: ['tabular-nums'],
  },
  // [- N +] 형태
  qtyControls: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 4,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  qtyBtn: {
    width: 24,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  qtyBtnText: {
    fontSize: fp(13),
    color: '#374151',
    fontWeight: '700',
    lineHeight: fp(16),
  },
  qtyNum: {
    minWidth: 24,
    paddingHorizontal: 2,
    textAlign: 'center',
    fontSize: fp(12),
    lineHeight: 22,
    fontWeight: '800',
    color: '#111827',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: '#e5e7eb',
  },
  cartItemSubtotal: {
    textAlign: 'right',
    fontSize: fp(12),
    fontWeight: '800',
    color: '#111827',
    fontVariant: ['tabular-nums'],
  },

  cartFooter: {
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    padding: 5,
    backgroundColor: '#fff',
    gap: 4,
  },
  cartFooterPhone: {
    padding: 4,
    gap: 3,
  },
  textCompact: { fontSize: fp(12) },
  totalValuePhone: { fontSize: fp(15) },
  selectedTableBarPhone: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderRadius: 7,
  },
  selectedTableLabelPhone: { fontSize: fp(12) },
  selectedTableValuePhone: { fontSize: fp(13) },
  payBtnPhone: {
    paddingVertical: 5,
    borderRadius: 5,
  },
  payBtnTextPhone: { fontSize: fp(11) },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  totalLabel: { fontSize: fp(12), color: '#374151', fontWeight: '600' },
  totalValue: { fontSize: fp(15), color: '#dc2626', fontWeight: '800' },
  changeRow: {
    paddingVertical: 2,
    paddingHorizontal: 6,
    backgroundColor: '#fffbeb',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#fde68a',
  },
  changeText: { fontSize: fp(10), color: '#92400e', fontWeight: '600' },
  changeAmount: { color: '#dc2626', fontWeight: '800', fontSize: fp(11) },
  changeShortage: { color: '#dc2626', fontWeight: '800' },
  clearBtn: {
    paddingVertical: 10,
    borderRadius: 6,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d1d5db',
    alignItems: 'center',
  },
  clearBtnDisabled: { backgroundColor: '#f3f4f6', borderColor: '#e5e7eb' },
  clearBtnText: { fontSize: fp(11), color: '#fff', fontWeight: '700' },
  clearBtnTextDisabled: { color: '#9ca3af' },

  paidBadge: {
    backgroundColor: '#ecfdf5',
    borderWidth: 1,
    borderColor: '#10b981',
    borderRadius: 6,
    paddingVertical: 8,
    alignItems: 'center',
  },
  paidBadgeText: { fontSize: fp(13), color: '#065f46', fontWeight: '700' },

  pendingNotice: {
    backgroundColor: '#fef3c7',
    borderWidth: 1,
    borderColor: '#f59e0b',
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  pendingNoticeText: {
    fontSize: fp(10),
    color: '#92400e',
    fontWeight: '700',
    textAlign: 'center',
    backgroundColor: '#fef3c7',
    borderRadius: 4,
    paddingVertical: 3,
    paddingHorizontal: 4,
  },

  selectedTableBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#eff6ff',
    borderWidth: 1,
    borderColor: '#2563eb',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 14,
    gap: 8,
  },
  selectedTableBarPending: {
    backgroundColor: '#fef3c7',
    borderColor: '#f59e0b',
  },
  selectedTableBarGroup: {
    backgroundColor: '#ede9fe',
    borderColor: '#7c3aed',
  },
  selectedTableLabel: {
    fontSize: fp(13),
    color: '#1e3a8a',
    fontWeight: '700',
  },
  selectedTableValue: {
    fontSize: fp(15),
    color: '#1d4ed8',
    fontWeight: '900',
    flexShrink: 1,
    textAlign: 'left',
  },
  selectedTableValuePending: {
    color: '#b45309',
  },
  selectedTableHint: {
    fontSize: fp(11),
    color: '#1d4ed8',
    fontWeight: '700',
    opacity: 0.75,
  },
  selectedTableHintPhone: {
    fontSize: fp(10),
  },

  // 결제 버튼 행 — B 풀솔리드 스타일 + 사용자 지정 색상
  // 주문(분홍) / 변경(빨강) / 삭제(파랑) / 선불(보라) / 후불(노랑)
  payRow: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  orderBtn: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 11,
    paddingHorizontal: 4,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: '#ec4899',
    borderColor: '#ec4899',
  },
  changeBtn: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 11,
    paddingHorizontal: 4,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: '#dc2626',
    borderColor: '#dc2626',
  },
  clearInlineBtn: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 11,
    paddingHorizontal: 4,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: '#2563eb',
    borderColor: '#2563eb',
  },
  prepaidBtn: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 11,
    paddingHorizontal: 4,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: '#8b5cf6',
    borderColor: '#8b5cf6',
  },
  postpaidBtn: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 11,
    paddingHorizontal: 4,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: '#facc15',
    borderColor: '#facc15',
  },
  payBtnDisabled: { opacity: 0.35 },
  payBtnText: {
    color: '#fff',
    fontSize: fp(11),
    fontWeight: '700',
  },
  // 후불(노랑) 위에는 검정 글자가 가독성 좋음
  postpaidBtnText: { color: '#111827' },

  clearTableBtn: {
    paddingVertical: 12,
    borderRadius: 6,
    backgroundColor: '#10b981',
    alignItems: 'center',
  },
  clearTableBtnText: { color: '#fff', fontSize: fp(14), fontWeight: '700' },
  });
}
