import { StyleSheet } from 'react-native';

// TableScreen.js 에서 분리된 스타일 시트.
// scale: useResponsive() 의 폰트 배율(lg=1.3, 그 외 1.0). PC/대형 태블릿 가독성 향상용.
//        fontSize / lineHeight 에만 곱함 — padding / borderRadius 등 레이아웃은 미변경.
export default function makeStyles(scale = 1) {
  const fp = (n) => Math.round(n * scale);
  return StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },

  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#fff',
  },
  topBarPhone: { paddingHorizontal: 6, paddingVertical: 2 },
  subTabs: { flexDirection: 'row', gap: 24 },
  subTabsPhone: { gap: 6 },
  subTab: {
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  subTabPhone: { paddingVertical: 4, paddingHorizontal: 2, borderBottomWidth: 2 },
  subTabActive: { borderBottomColor: '#111827' },
  subTabText: { fontSize: fp(8), color: '#9ca3af', fontWeight: '500' },
  subTabTextPhone: { fontSize: fp(8) },
  subTabTextActive: { color: '#111827', fontWeight: '700' },

  actions: { flexDirection: 'row', gap: 6, alignItems: 'center' },
  actionBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 4,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d1d5db',
  },
  actionBtnPhone: { paddingVertical: 3, paddingHorizontal: 6 },
  actionBtnText: { fontSize: fp(8), color: '#374151', fontWeight: '500' },
  actionBtnTextPhone: { fontSize: fp(8) },
  actionBtnActive: { backgroundColor: '#2563eb', borderColor: '#2563eb' },
  actionBtnTextActive: { color: '#fff', fontWeight: '700' },
  settingBtn: { padding: 6, marginLeft: 4 },
  settingIcon: { fontSize: fp(8), color: '#6b7280' },
  allMapBtn: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: '#1f2937',
    borderRadius: 6,
    marginLeft: 4,
  },
  allMapBtnText: { fontSize: fp(8), color: '#f9fafb', fontWeight: '700' },

  hintBar: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: '#eff6ff',
    borderBottomWidth: 1,
    borderBottomColor: '#bfdbfe',
  },
  hintText: { color: '#1e3a8a', fontSize: fp(8), fontWeight: '600' },
  moveHint: { backgroundColor: '#fef3c7', borderBottomColor: '#fcd34d' },
  moveHintText: { color: '#92400e', fontSize: fp(8), fontWeight: '700' },
  groupHint: { backgroundColor: '#ede9fe', borderBottomColor: '#c4b5fd' },
  groupHintText: { color: '#5b21b6', fontSize: fp(8), fontWeight: '700' },
  groupHintSelected: {
    color: '#6d28d9',
    fontSize: fp(8),
    fontWeight: '800',
    marginTop: 2,
  },

  grid: {
    flex: 1,
    flexDirection: 'column',
    gap: 10,
    padding: 16,
  },
  gridPhone: { gap: 4, padding: 4 },
  // 그리드 행 안에서 스트립이 차지하는 셀 영역 — flex 로 폭 결정
  stripCell: { minHeight: 0, alignSelf: 'stretch' },
  gridFit: { flex: 1, alignContent: 'flex-start' },
  gridRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'stretch',
    minHeight: 0,
  },
  tile: {
    minHeight: 0,
    borderWidth: 2,
    borderRadius: 8,
    backgroundColor: '#fff',
    padding: 4,
  },
  tilePhone: { borderRadius: 6, padding: 3 },
  tileTouch: { flex: 1 },
  // height 는 tileHeight(동적 계산값) 으로 덮어씌움 — 여기서는 정렬만 지정
  tileEmpty: { justifyContent: 'center', alignItems: 'center' },
  tileEmptyPhone: { justifyContent: 'center', alignItems: 'center' },
  tileWithOrder: {},
  tileReady: { backgroundColor: '#ecfdf5', borderColor: '#10b981' },
  tileCooking: { backgroundColor: '#fff7ed', borderColor: '#f97316' },
  tilePaid: { backgroundColor: '#eff6ff', borderColor: '#2563eb' },
  tileDelivering: { backgroundColor: '#faf5ff', borderColor: '#a855f7' },
  tileOrdering: { backgroundColor: '#fef3c7', borderColor: '#f59e0b' },
  tileGrouped: { backgroundColor: '#ede9fe', borderColor: '#7c3aed' },
  tileGroupSelected: {
    backgroundColor: '#c4b5fd',
    borderColor: '#6d28d9',
    borderWidth: 3,
  },
  // 선택된 테이블을 전체 깜빡이는 컬러로 표시 — blinkOn 일 때만 적용되어 깜빡임 효과
  tileHighlightedBlink: {
    backgroundColor: '#60a5fa',
    borderColor: '#1d4ed8',
  },

  splitSlot: {
    flexDirection: 'row',
    gap: 4,
    alignItems: 'stretch',
    minHeight: 0,
  },
  tilePart: {
    flex: 1,
    minHeight: 0,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderRadius: 8,
    backgroundColor: '#fff',
    padding: 6,
  },
  tilePartPhone: { borderRadius: 6, padding: 3 },

  // 일반 테이블 라벨 — 총가격(11px)과 동일한 크기로 통일.
  // flexShrink: 0 — 라벨은 절대 잘리지 않도록 (총가격이 ellipsize 됨).
  tileLabel: { fontSize: fp(11), color: '#374151', fontWeight: '700', flexShrink: 0 },
  tileLabelTiny: { fontSize: fp(8), color: '#374151', fontWeight: '700', flexShrink: 0 },
  // 주문 없는 빈(대기) 테이블 — 식별이 쉽도록 라벨을 키움
  tileLabelEmpty: { fontSize: fp(15), color: '#374151', fontWeight: '900' },
  textTiny: { fontSize: fp(9) },

  tileTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 1,
    gap: 4,
  },
  tileTopLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flexShrink: 1,
    minWidth: 0,
  },
  // 테이블 라벨 우측에 가독성 있게 표시되는 총 금액
  tileTopTotal: {
    fontSize: fp(11),
    color: '#dc2626',
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  tileTopTotalTiny: {
    fontSize: fp(9),
  },
  tileTopTotalPaid: {
    color: '#10b981',
  },
  // 주문 진행 중 테이블 — 총가격(11px) 옆 라벨도 동일 크기. 라벨 잘림 방지.
  tileLabelSmall: { fontSize: fp(11), color: '#111827', fontWeight: '800', flexShrink: 0 },
  badgesWrap: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  tileQtyBadge: {
    fontSize: fp(8),
    color: '#fff',
    fontWeight: '700',
    backgroundColor: '#dc2626',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    overflow: 'hidden',
  },
  tileReadyBadge: {
    fontSize: fp(8),
    color: '#fff',
    fontWeight: '700',
    backgroundColor: '#10b981',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    overflow: 'hidden',
  },
  tileCookingBadge: {
    fontSize: fp(8),
    color: '#fff',
    fontWeight: '700',
    backgroundColor: '#f97316',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    overflow: 'hidden',
  },
  tilePaidBadge: {
    fontSize: fp(8),
    color: '#fff',
    fontWeight: '700',
    backgroundColor: '#2563eb',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    overflow: 'hidden',
  },
  // 조리완료 미결제 시 표시되는 큰 결제완료 버튼.
  // 뱃지보다 폰트/패딩이 커서 한 번에 누르기 좋음. 색은 주의 환기용 amber 톤.
  tilePayBtn: {
    backgroundColor: '#f59e0b',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#d97706',
    alignItems: 'center',
  },
  // 결제하기 버튼 안 금액 — 버튼이 tileTopLeft 금액을 밀어내는 문제 방지용.
  tilePayBtnTotal: {
    fontSize: fp(12),
    color: '#7c2d12',
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  tilePayBtnText: {
    fontSize: fp(11),
    color: '#fff',
    fontWeight: '800',
  },
  // 1.0.23: 포장 결제완료 + 조리완료 시 "픽업 완료" 버튼.
  // 결제완료 amber 와 시각적 구분 — 초록 톤 (완료 / 마무리 의미).
  tilePickupBtn: {
    backgroundColor: '#10b981',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#059669',
    alignItems: 'center',
    marginTop: 4,
  },
  tilePickupBtnText: {
    fontSize: fp(10),
    color: '#fff',
    fontWeight: '800',
  },
  tileDeliveringBadge: {
    fontSize: fp(8),
    color: '#fff',
    fontWeight: '700',
    backgroundColor: '#a855f7',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    overflow: 'hidden',
  },

  tileOrderingWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    gap: 4,
  },
  tileEmptyWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    gap: 4,
  },
  tileOrderingBadge: {
    fontSize: fp(8),
    color: '#fff',
    fontWeight: '800',
    backgroundColor: '#f59e0b',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 10,
    overflow: 'hidden',
  },
  tileGroupBadge: {
    fontSize: fp(8),
    color: '#fff',
    fontWeight: '800',
    backgroundColor: '#7c3aed',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    overflow: 'hidden',
  },

  deliveryAddr: {
    fontSize: fp(9),
    lineHeight: fp(11),
    color: '#dc2626',
    fontWeight: '700',
    marginTop: 1,
    marginBottom: 2,
    paddingHorizontal: 2,
    backgroundColor: '#fef2f2',
    borderRadius: 2,
    // flex 부모 안에서 다른 항목에 의해 압축되어 0 높이로 가려지는 것 방지
    flexShrink: 0,
  },
  deliveryRequest: {
    fontSize: fp(9),
    lineHeight: fp(11),
    color: '#9a3412',
    fontWeight: '800',
    marginTop: 1,
    marginBottom: 2,
    paddingHorizontal: 3,
    backgroundColor: '#fff7ed',
    borderRadius: 2,
    borderLeftWidth: 2,
    borderLeftColor: '#ea580c',
    flexShrink: 0,
  },
  // 4행 무조건 보장: lineHeight 13 × 4 + gap 1 × 3 = 55.
  // flexShrink: 0 으로 다른 요소가 공간을 뺏지 못하게 막음.
  // 다른 요소 (delivery / total) 가 잘릴 수는 있어도 메뉴 4개는 반드시 표시.
  orderItemsList: {
    marginTop: 1,
    marginBottom: 1,
    gap: 1,
    flexShrink: 0,
    flexGrow: 0,
    minHeight: fp(13) * 4 + 3,
  },
  orderItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 6,
  },
  orderItemName: { fontSize: fp(10), color: '#374151', flex: 1, lineHeight: fp(13) },
  largeTag: { color: '#dc2626', fontWeight: '800' },
  normalTag: { color: '#6b7280', fontWeight: '600' },
  optTag: { color: '#2563eb', fontWeight: '700', fontSize: fp(8) },
  // 메모는 항목 위 최상단에 작은 강조 박스로 — 옵션보다 더 눈에 띄게
  itemMemo: {
    fontSize: fp(9),
    color: '#92400e',
    fontWeight: '700',
    backgroundColor: '#fffbeb',
    borderLeftWidth: 2,
    borderLeftColor: '#f59e0b',
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 3,
    marginBottom: 1,
  },
  itemMemoModal: {
    fontSize: fp(11),
    color: '#92400e',
    fontWeight: '700',
    backgroundColor: '#fffbeb',
    borderLeftWidth: 3,
    borderLeftColor: '#f59e0b',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    marginBottom: 4,
  },
  itemCookedText: {
    color: '#10b981',
    textDecorationLine: 'line-through',
  },
  itemCookedBadge: {
    color: '#065f46',
    fontSize: fp(9),
    fontWeight: '800',
  },
  itemCookingText: {
    color: '#c2410c',
    fontWeight: '700',
  },
  itemCookingBadge: {
    color: '#9a3412',
    fontSize: fp(9),
    fontWeight: '800',
  },
  orderItemQty: { fontSize: fp(10), color: '#6b7280', fontWeight: '700' },
  orderItemsMore: {
    fontSize: fp(10),
    color: '#6b7280',
    fontStyle: 'italic',
    fontWeight: '600',
    marginTop: 2,
  },
  // top row 뱃지 영역에 들어가는 펼쳐보기 칩 — 라벨/총가격 침범 안 하도록 좁게,
  // 단 패딩은 1~2 확보해 손가락 탭 영역 유지. 원본(4/0/7px) 대비 패딩+폰트 모두 향상.
  expandChip: {
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 6,
    backgroundColor: '#eef2ff',
    borderWidth: 1,
    borderColor: '#c7d2fe',
  },
  expandChipText: {
    fontSize: fp(9),
    color: '#3730a3',
    fontWeight: '700',
  },
  expandBtn: {
    marginTop: 3,
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderRadius: 10,
    backgroundColor: '#eef2ff',
    borderWidth: 1,
    borderColor: '#c7d2fe',
    alignSelf: 'flex-start',
    flexShrink: 0,
  },
  expandBtnText: {
    fontSize: fp(8),
    color: '#3730a3',
    fontWeight: '700',
  },
  // <Modal> 대체 풀스크린 오버레이
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 9999,
    elevation: 9999,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalCard: {
    width: '100%',
    maxWidth: 480,
    maxHeight: '80%',
    backgroundColor: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  modalTitle: { fontSize: fp(14), fontWeight: '800', color: '#111827' },
  modalCloseHint: {
    fontSize: fp(11),
    color: '#9ca3af',
    fontStyle: 'italic',
  },
  modalBody: { paddingHorizontal: 12, paddingTop: 6 },
  modalItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  modalItemName: { flex: 1, fontSize: fp(12), color: '#111827', fontWeight: '600' },
  modalItemQty: {
    minWidth: 36,
    textAlign: 'right',
    fontSize: fp(11),
    color: '#6b7280',
    fontWeight: '600',
  },
  modalItemSubtotal: {
    minWidth: 72,
    textAlign: 'right',
    fontSize: fp(11),
    color: '#111827',
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  modalFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  modalTotalLabel: { fontSize: fp(12), color: '#6b7280', fontWeight: '600' },
  modalTotalValue: { fontSize: fp(13), fontWeight: '800', color: '#111827' },
  orderTotal: {
    marginTop: 'auto',
    paddingTop: 2,
    fontSize: fp(9),
    color: '#111827',
    fontWeight: '700',
    textAlign: 'right',
    flexShrink: 0,
  },
  orderTotalTiny: { fontSize: fp(9) },

  clearTableBtn: {
    marginTop: 6,
    paddingVertical: 8,
    borderRadius: 4,
    backgroundColor: '#10b981',
    alignItems: 'center',
  },
  clearTableBtnText: { color: '#fff', fontSize: fp(11), fontWeight: '700' },
  });
}
