export const categories = [
  '즐겨찾기',
  '밀면',
  '국수/만백',
  '팥',
  '만두/공기밥',
  '음료',
];

export const menuItems = [
  {
    id: 1,
    name: '칼국수',
    shortName: '칼',
    price: 7000,
    color: '#8EA5B1',
    category: '국수/만백',
    favorite: true,
    sizeGroup: 'milkalsu',
    sizeUpcharge: 1000,
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Korean.noodle-Kalguksu-01.jpg/500px-Korean.noodle-Kalguksu-01.jpg',
  },
  {
    id: 2,
    name: '수제비',
    shortName: '수제비',
    price: 7000,
    color: '#B495BC',
    category: '국수/만백',
    favorite: true,
    sizeGroup: 'milkalsu',
    sizeUpcharge: 1000,
    image: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Sujebi.jpg',
  },
  {
    id: 3,
    name: '칼제비',
    shortName: '칼제비',
    price: 7000,
    color: '#5A6575',
    category: '국수/만백',
    favorite: true,
    sizeGroup: 'milkalsu',
    sizeUpcharge: 1000,
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Kaljebi.jpg/500px-Kaljebi.jpg',
  },
  {
    id: 4,
    name: '만두백반',
    shortName: '만백',
    price: 7000,
    color: '#E8C54A',
    category: '만두/공기밥',
    favorite: true,
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Korean_cuisine-Kalguksu_and_mandu.jpg/500px-Korean_cuisine-Kalguksu_and_mandu.jpg',
  },
  {
    id: 5,
    name: '들깨칼국수',
    shortName: '들깨',
    price: 9000,
    color: '#E5C87A',
    category: '국수/만백',
    favorite: true,
    sizeGroup: 'deulpatkong',
    sizeUpcharge: 2000,
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Deulkkae-chik-kal-guksu.jpg/500px-Deulkkae-chik-kal-guksu.jpg',
  },
  {
    id: 6,
    name: '팥칼국수',
    shortName: '팥칼',
    price: 9000,
    color: '#C9A876',
    category: '팥',
    favorite: true,
    sizeGroup: 'deulpatkong',
    sizeUpcharge: 2000,
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Pat_kalguksu_%28red_bean_noodles%29.jpg/500px-Pat_kalguksu_%28red_bean_noodles%29.jpg',
  },
  {
    id: 7,
    name: '새알팥',
    shortName: '새알',
    price: 11000,
    color: '#8DA869',
    category: '팥',
    favorite: true,
    sizeGroup: 'deulpatkong',
    sizeUpcharge: 2000,
    image:
      'https://upload.wikimedia.org/wikipedia/commons/e/ec/Patjuk_%28red_bean_porridge%29.jpg',
  },
  {
    id: 8,
    name: '팥반반(칼+새알)',
    shortName: '반반',
    price: 11000,
    color: '#D48B8A',
    category: '팥',
    favorite: true,
    sizeGroup: 'deulpatkong',
    sizeUpcharge: 2000,
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Pat_kalguksu_%28red_bean_noodles%29.jpg/500px-Pat_kalguksu_%28red_bean_noodles%29.jpg',
  },
  {
    id: 9,
    name: '동지팥죽(밥알+새알)',
    shortName: '동지',
    price: 11000,
    color: '#8C5E4D',
    category: '팥',
    favorite: true,
    sizeGroup: 'deulpatkong',
    sizeUpcharge: 2000,
    image:
      'https://upload.wikimedia.org/wikipedia/commons/e/ec/Patjuk_%28red_bean_porridge%29.jpg',
  },
  {
    id: 10,
    name: '팥죽(밥알)',
    shortName: '팥죽',
    price: 11000,
    color: '#5A91C4',
    category: '팥',
    favorite: true,
    sizeGroup: 'deulpatkong',
    sizeUpcharge: 2000,
    image:
      'https://upload.wikimedia.org/wikipedia/commons/e/ec/Patjuk_%28red_bean_porridge%29.jpg',
  },
  {
    id: 11,
    name: '고기만두',
    shortName: '만두',
    price: 4000,
    color: '#A0B066',
    category: '만두/공기밥',
    favorite: true,
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Gogi-mandu.jpg/500px-Gogi-mandu.jpg',
  },
  {
    id: 12,
    name: '감자피만두',
    shortName: '감자',
    price: 4000,
    color: '#4D5B8F',
    category: '만두/공기밥',
    favorite: true,
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Jjinmandu.jpg/500px-Jjinmandu.jpg',
  },
  {
    id: 13,
    name: '밀면',
    shortName: '물',
    price: 7000,
    color: '#D8836A',
    category: '밀면',
    favorite: true,
    sizeGroup: 'milkalsu',
    sizeUpcharge: 1000,
    image:
      'https://upload.wikimedia.org/wikipedia/commons/9/9c/Korean_cold_noodle_soup-Milmyeon-01.jpg',
  },
  {
    id: 14,
    name: '비빔밀면',
    shortName: '비빔',
    price: 7000,
    color: '#B86050',
    category: '밀면',
    favorite: true,
    sizeGroup: 'milkalsu',
    sizeUpcharge: 1000,
    image:
      'https://upload.wikimedia.org/wikipedia/commons/b/ba/Boiled_jjolmyeon.jpg',
  },
  {
    id: 15,
    name: '물비빔',
    shortName: '물비빔',
    price: 7000,
    color: '#C47970',
    category: '밀면',
    favorite: true,
    sizeGroup: 'milkalsu',
    sizeUpcharge: 1000,
    image:
      'https://upload.wikimedia.org/wikipedia/commons/5/58/Naengmyeon_%28cold_noodles%29.jpg',
  },
  {
    id: 16,
    name: '들깨수제비',
    shortName: '들깨수제',
    price: 9000,
    color: '#D4C488',
    category: '국수/만백',
    image: '',
    sizeGroup: 'deulpatkong',
    sizeUpcharge: 2000,
  },
  {
    id: 17,
    name: '콩국수',
    shortName: '콩국수',
    price: 8000,
    color: '#EEE9D5',
    category: '국수/만백',
    image: '',
    sizeGroup: 'deulpatkong',
    sizeUpcharge: 2000,
  },
  {
    id: 18,
    name: '떡만두국',
    shortName: '떡만',
    price: 8000,
    color: '#C8A172',
    category: '국수/만백',
    image: '',
  },
  {
    id: 19,
    name: '들깨새알',
    shortName: '들깨새알',
    price: 10000,
    color: '#A5C77C',
    category: '국수/만백',
    image: '',
    sizeGroup: 'deulpatkong',
    sizeUpcharge: 2000,
  },
  {
    id: 20,
    name: '온국수',
    shortName: '온국수',
    price: 7000,
    color: '#A0ADAE',
    category: '국수/만백',
    image: '',
    sizeGroup: 'milkalsu',
    sizeUpcharge: 1000,
  },
  {
    id: 21,
    name: '사리추가',
    shortName: '사리',
    price: 2000,
    color: '#E3D088',
    category: '만두/공기밥',
    image: '',
  },
  {
    id: 22,
    name: '공기밥',
    shortName: '공기밥',
    price: 1000,
    color: '#F2EBD6',
    category: '만두/공기밥',
    image: '',
  },
  {
    id: 23,
    name: '구운계란',
    shortName: '계란',
    price: 1000,
    color: '#E8B878',
    category: '만두/공기밥',
    image: '',
  },
  {
    id: 24,
    name: '사이다',
    shortName: '사이다',
    price: 2000,
    color: '#88C5A8',
    category: '음료',
    image: '',
  },
  {
    id: 25,
    name: '콜라',
    shortName: '콜라',
    price: 2000,
    color: '#4C2E1F',
    category: '음료',
    image: '',
  },
];

export const defaultCategoryRows = {
  // 모든 카테고리를 동일하게 고정 6×4 격자(빈 슬롯 null) 로 관리.
  // 사용자가 드래그로 자유 재배치 가능.
  '즐겨찾기': [
    [1, 2, 3, 4, null, null],
    [5, 6, 7, 8, 9, 10],
    [11, 12, null, null, null, null],
    [13, 14, 15, null, null, null],
  ],
  '국수/만백': [
    [1, 2, 3, 4, 5, 16],
    [17, 18, 19, 20, null, null],
    [null, null, null, null, null, null],
    [null, null, null, null, null, null],
  ],
  '팥': [
    [6, 7, 8, 9, 10, null],
    [null, null, null, null, null, null],
    [null, null, null, null, null, null],
    [null, null, null, null, null, null],
  ],
  '만두/공기밥': [
    [11, 12, 21, 22, 23, null],
    [null, null, null, null, null, null],
    [null, null, null, null, null, null],
    [null, null, null, null, null, null],
  ],
  '음료': [
    [24, 25, null, null, null, null],
    [null, null, null, null, null, null],
    [null, null, null, null, null, null],
    [null, null, null, null, null, null],
  ],
  '밀면': [
    [13, 14, 15, null, null, null],
    [null, null, null, null, null, null],
    [null, null, null, null, null, null],
    [null, null, null, null, null, null],
  ],
};

// 사이즈 옵션 — 메뉴별 sizeGroup 과 매칭되며 사용자가 변경/이동할 수 없음.
export const sizeOptions = [
  { id: 'opt1', label: '대(밀,칼,수)', price: 1000, sizeGroup: 'milkalsu' },
  { id: 'opt2', label: '대(들,팥,콩)', price: 2000, sizeGroup: 'deulpatkong' },
];

// 사용자 편집 가능한 토글 옵션 — 라벨/순서 변경 가능. 메모는 별도 자유 입력.
export const defaultEditableOptions = [
  { id: 'opt3', label: '면적게' },
  { id: 'opt4', label: '땡초빼고' },
  { id: 'opt5', label: '싱겁게' },
  { id: 'opt7', label: '덜맵게' },
  { id: 'opt8', label: '얼음빼고' },
  { id: 'opt9', label: '오이빼고' },
  { id: 'opt10', label: '포장' },
];

// 하위호환: 전체 옵션 카탈로그 (사이즈 + 편집 옵션 기본값)
export const options = [...sizeOptions, ...defaultEditableOptions];
